pipeline {
    agent any 
    stages {
        // stage('Flutter Doctor') {
        //     steps {
        //         sh 'flutter doctor -v'
        //     }
        // }
        stage('Test') {
               steps {
            sh 'flutter test test/unit_test.dart'
        }
        }
        stage('Build web'){
               steps {
             sh 'flutter build web --release'
        }
        }
        stage('flutter clean'){
               steps {
            sh 'flutter clean'
        }
        }
    }
}
