pipeline {
    agent any 
    stages {
        stage('Flutter Doctor') {
            steps {
                sh 'flutter doctor -v'
            }
        }
        stages('Test') {
            sh 'flutter test test/unit_test.dart'
        }
        stage('Build web'){
             sh 'flutter build web --release'
        }
    }
}
